# Generated by Django 4.0 on 2023-05-10 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='profile_pic/profile.png', null=True, upload_to='profile_pic')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('members_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('img', models.ImageField(blank=True, default='groups_pics/group.png', null=True, upload_to='groups_pics')),
                ('description', models.TextField(default='Welcome to the group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.userprofile')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='Chat.UserProfile')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='Chat.grouptype')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat-files/')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('ftype', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Chat.group')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='Chat.chat')),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to='Chat.userprofile')),
            ],
        ),
    ]
